<?php
$aLang = array(
    'charset' => 'utf-8',

    'SHOP_MODULE_GROUP_sKussinChatGptSettings' => 'ChatGPT api settings',
    'SHOP_MODULE_sKussinChatGptApiKey' => 'ChatGPT api key',
    'SHOP_MODULE_sKussinChatGptApiModel' => 'ChatGPT api model',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-4' => 'GPT-4',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo' => 'GPT-3.5 Turbo',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo-0301' => 'GPT-3.5 Turbo (0301)',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo-1107' => 'GPT-3.5 Turbo (1107)',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3' => 'GPT-3',
    'SHOP_MODULE_dKussinChatGptApiTemperature' => 'ChatGPT api temperature',
    'SHOP_MODULE_iKussinChatGptApiMaxTokens' => 'ChatGPT api max tokens',
    'SHOP_MODULE_blKussinChatGptArticleDataEnhancerEnabled' => 'Enable Kussin | Article Data Enhancer for OXID eShop',
    'SHOP_MODULE_sKussinChatGptArticleDataEnhancerArticleIdKey' => 'Article id key (e.g. oxarticles__oxartnum) for Kussin | Article Data Enhancer for OXID eShop',

    'SHOP_MODULE_GROUP_sKussinChatGptFrontendSettings' => 'Frontend settings',
    'SHOP_MODULE_blKussinChatGptFrontendDisclaimerEnabled' => 'Enable disclaimer',
    'SHOP_MODULE_sKussinChatGptFrontendDisclaimerCmsId' => 'Disclaimer content id',

    'SHOP_MODULE_GROUP_sKussinChatGptPromptContextSettings' => 'Prompt context settings',
    'SHOP_MODULE_sKussinChatGptPromptContext' => 'Add context to prompt (e.g. company informations)',

    'SHOP_MODULE_GROUP_sKussinChatGptPromptSettings' => 'Prompt settings',
    'SHOP_MODULE_sKussinChatGptPromptLongDescriptionDE' => 'Prompt for article long description (German)',
    'SHOP_MODULE_sKussinChatGptPromptLongDescriptionEN' => 'Prompt for article long description (English)',
    'SHOP_MODULE_sKussinChatGptPromptShortDescriptionDE' => 'Prompt for article short description (German)',
    'SHOP_MODULE_sKussinChatGptPromptShortDescriptionEN' => 'Prompt for article short description (English)',
    'SHOP_MODULE_sKussinChatGptPromptProductSearchKeysDE' => 'Prompt for article search terms (German)',
    'SHOP_MODULE_sKussinChatGptPromptProductSearchKeysEN' => 'Prompt for article search terms (English)',
    'SHOP_MODULE_sKussinChatGptPromptProductAttributesDE' => 'Prompt for article attributes (German)',
    'SHOP_MODULE_sKussinChatGptPromptProductAttributesEN' => 'Prompt for article attributes (English)',
    'SHOP_MODULE_sKussinChatGptPromptOptimizeContentDE' => 'Prompt for optimize content (German)',
    'SHOP_MODULE_sKussinChatGptPromptOptimizeContentEN' => 'Prompt for optimize content (English)',
    'SHOP_MODULE_sKussinChatGptPromptWeight' => 'Prompt for article weight (oxweight)',

    'SHOP_MODULE_GROUP_sKussinChatGptProcessSettings' => 'Process queue settings',
    'SHOP_MODULE_blKussinChatGptProcessQueueEnabled' => 'Enable debug mode',
    'SHOP_MODULE_sKussinChatGptProcessSelectionQuery' => 'ChatGPT content selection sql statement',
    'SHOP_MODULE_sKussinChatGptProcessModel' => 'ChatGPT api model',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-4' => 'GPT-4',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo' => 'GPT-3.5 Turbo',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo-0301' => 'GPT-3.5 Turbo (0301)',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo-1107' => 'GPT-3.5 Turbo (1107)',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3' => 'GPT-3',
    'SHOP_MODULE_dKussinChatGptProcessTemperature' => 'ChatGPT api temperature',
    'SHOP_MODULE_iKussinChatGptProcessMaxTokens' => 'ChatGPT api max tokens',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxPrompts' => 'Max. data rows to create prompts',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxGenerations' => 'Max. data rows to generate ai content',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxReplacements' => 'Max. data rows to replace with ai content',
    'SHOP_MODULE_sKussinChatGptProcessProductAttributesForbiddenValues' => 'Comma-separated list of forbidden attribute values',
    'SHOP_MODULE_blKussinChatGptProcessQueueAutoApprovedEnabled' => 'Enable auto publish for process queue',

    'SHOP_MODULE_GROUP_sKussinChatGptWeightSettings' => 'Weight settings',
    'SHOP_MODULE_sKussinChatGptWeightQueryTimestamp' => 'Select query start date',
    'SHOP_MODULE_sKussinCategoryWeightRanges' => 'Category weight range',

    'SHOP_MODULE_GROUP_sKussinChatGptDebugSettings' => 'Debug settings',
    'SHOP_MODULE_blKussinChatGptDebugEnabled' => 'Enable debug mode',
    'SHOP_MODULE_sKussinChatGptDebugLogFilename' => 'Define debug log filename',
);