<?php
$aLang = array(
    'charset' => 'utf-8',

    'SHOP_MODULE_GROUP_sKussinChatGptSettings' => 'ChatGPT API Einstellungen',
    'SHOP_MODULE_sKussinChatGptApiKey' => 'ChatGPT API KEY',
    'SHOP_MODULE_sKussinChatGptApiModel' => 'ChatGPT API Model',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-4' => 'GPT-4',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo' => 'GPT-3.5 Turbo',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo-0301' => 'GPT-3.5 Turbo (0301)',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3.5-turbo-1107' => 'GPT-3.5 Turbo (1107)',
    'SHOP_MODULE_sKussinChatGptApiModel_gpt-3' => 'GPT-3',
    'SHOP_MODULE_dKussinChatGptApiTemperature' => 'ChatGPT API Temperature',
    'SHOP_MODULE_iKussinChatGptApiMaxTokens' => 'ChatGPT API max. Tokens',
    'SHOP_MODULE_blKussinChatGptArticleDataEnhancerEnabled' => 'Kussin | Article Data Enhancer for OXID eShop aktivieren',
    'SHOP_MODULE_sKussinChatGptArticleDataEnhancerArticleIdKey' => 'Artikel-ID-Key (z.B. oxarticles__oxartnum) für Kussin | Article Data Enhancer für OXID eShop',

    'SHOP_MODULE_GROUP_sKussinChatGptFrontendSettings' => 'Shop (Frontend) Einstellungen',
    'SHOP_MODULE_blKussinChatGptFrontendDisclaimerEnabled' => 'Disclaimer aktivieren',
    'SHOP_MODULE_sKussinChatGptFrontendDisclaimerCmsId' => 'Disclaimer Content Id',

    'SHOP_MODULE_GROUP_sKussinChatGptPromptContextSettings' => 'Prompt Kontext Einstellungen',
    'SHOP_MODULE_sKussinChatGptPromptContext' => 'Kontext zu Prompt hinzufügen (z.B. Firmeninformationen)',

    'SHOP_MODULE_GROUP_sKussinChatGptPromptSettings' => 'Prompt Einstellungen',
    'SHOP_MODULE_sKussinChatGptPromptLongDescriptionDE' => 'Prompt für Artikel-Langbeschreibung (Deutsch)',
    'SHOP_MODULE_sKussinChatGptPromptLongDescriptionEN' => 'Prompt für Artikel-Langbeschreibung (Englisch)',
    'SHOP_MODULE_sKussinChatGptPromptShortDescriptionDE' => 'Prompt für Artikel-Kurzbeschreibung (Deutsch)',
    'SHOP_MODULE_sKussinChatGptPromptShortDescriptionEN' => 'Prompt für Artikel-Kurzbeschreibung (Englisch)',
    'SHOP_MODULE_sKussinChatGptPromptProductSearchKeysDE' => 'Prompt für Artikel-Suchbegriffe (Deutsch)',
    'SHOP_MODULE_sKussinChatGptPromptProductSearchKeysEN' => 'Prompt für Artikel-Suchbegriffe (Englisch)',
    'SHOP_MODULE_sKussinChatGptPromptProductAttributesDE' => 'Prompt für Artikel-Attribute (Deutsch)',
    'SHOP_MODULE_sKussinChatGptPromptProductAttributesEN' => 'Prompt für Artikel-Attribute (Englisch)',
    'SHOP_MODULE_sKussinChatGptPromptOptimizeContentDE' => 'Prompt zur Optimierung des Inhalts (Deutsch)',
    'SHOP_MODULE_sKussinChatGptPromptOptimizeContentEN' => 'Prompt zur Optimierung des Inhalts (Englisch)',
    'SHOP_MODULE_sKussinChatGptPromptWeight' => 'Prompt für Artikel-Gewichts (oxweight)',

    'SHOP_MODULE_GROUP_sKussinChatGptProcessSettings' => 'Process Queue Einstellungen',
    'SHOP_MODULE_blKussinChatGptProcessQueueEnabled' => 'Aktivere Process Queue',
    'SHOP_MODULE_sKussinChatGptProcessSelectionQuery' => 'ChatGPT Content Selection SQL Statement',
    'SHOP_MODULE_sKussinChatGptProcessModel' => 'ChatGPT API Model',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-4' => 'GPT-4',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo' => 'GPT-3.5 Turbo',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo-0301' => 'GPT-3.5 Turbo (0301)',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3.5-turbo-1107' => 'GPT-3.5 Turbo (1107)',
    'SHOP_MODULE_sKussinChatGptProcessModel_gpt-3' => 'GPT-3',
    'SHOP_MODULE_dKussinChatGptProcessTemperature' => 'ChatGPT API Temperature',
    'SHOP_MODULE_iKussinChatGptProcessMaxTokens' => 'ChatGPT API max. Tokens',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxPrompts' => 'Max. Datensätze zur Erstellung von Prompts',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxGenerations' => 'Max. Datensätze zur Generierung von AI Content',
    'SHOP_MODULE_iKussinChatGptProcessLimitMaxReplacements' => 'Max. Datensätze zu Ersetzen durch AI Content',
    'SHOP_MODULE_sKussinChatGptProcessProductAttributesForbiddenValues' => 'CSV Liste von verbotenen Attribute-Werten',
    'SHOP_MODULE_blKussinChatGptProcessQueueAutoApprovedEnabled' => 'Aktiviere Auto-Publish für Process Queue',

    'SHOP_MODULE_GROUP_sKussinChatGptWeightSettings' => 'Weight settings',
    'SHOP_MODULE_sKussinChatGptWeightQueryTimestamp' => 'Select query start date',
    'SHOP_MODULE_sKussinCategoryWeightRanges' => 'Category weight range',

    'SHOP_MODULE_GROUP_sKussinChatGptDebugSettings' => 'Debug Einstellungen',
    'SHOP_MODULE_blKussinChatGptDebugEnabled' => 'Aktivere Debug Mode',
    'SHOP_MODULE_sKussinChatGptDebugLogFilename' => 'Debug Log Dateiname',
);